name: Deploy Frontend to Contabo VM

on:
  push:
    branches:
      - main # Ou a branch que dispara o deploy do frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build React App
        run: REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} CI='' yarn build
        env:
          NODE_ENV: production

      - name: Setup SSH for Contabo VM
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.CONTABO_SSH_KEY }}

      - name: Deploy Frontend Files to Contabo VM
        run: |
          # Defina o diretório de destino na VM
          VM_FRONTEND_DIR="/home/admin/frontend"
          # Use sudo para criar o diretório e depois mude o proprietário para o usuário admin
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.CONTABO_SSH_PORT || 22 }} admin@${{ secrets.CONTABO_HOST }} "sudo mkdir -p $VM_FRONTEND_DIR && sudo chown admin:admin $VM_FRONTEND_DIR"
          # Copie os arquivos da pasta build para o diretório na VM (agora o admin tem permissão)
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.CONTABO_SSH_PORT || 22 }}" \
            ./build/ admin@${{ secrets.CONTABO_HOST }}:$VM_FRONTEND_DIR/
